<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|    http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
//$config['base_url'] = 'https://www.swanntechnologies.com/OscarsBallotPredictions/';
$config['base_url'] = 'http://localhost/oscaraward/';
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = sys_get_temp_dir();
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/


$config['problems'] = array(
    		array('title'=>'Best Picture', 'score'=>10, 'data'=>array(
				'THE FATHER',
                'JUDAS AND THE BLACK MESSIAH',
                'MANK',
                'MINARI',
                'NOMADLAND',
                'PROMISING YOUNG WOMAN',
                'SOUND OF METAL',
                'THE TRIAL OF THE CHICAGO 7',
			)),
			array('title'=>'Best Director', 'score'=>7, 'data'=>array(
				'Thomas Vinterberg, “ANOTHER ROUND” ',
				'David Fincher, “MANK”',
				'Lee Isaac Chung, “MINARI”',
				'Chloe Zhao, “NOMADLAND”',
				'Emerald Fennell, “PROMISING YOUNG WOMAN”'
			)),
			array('title'=>'Best Actor', 'score'=>7, 'data'=>array(
				'Riz Ahmed “Sound of Metal”',
				'Chadwick Boseman “Ma Rainey black bottom”',
				'Anthony Hopkins “The Father”',
				'Gray Oldman “Mank”',
				'Steven Yeun “Minari”'
			)),
			array('title'=>'Best Actress', 'score'=>7, 'data'=>array(
				'Vlola Davis “Ma Raineys Black Bottom”',
				'Andra Day “The United States vs. Billie Holiday”',
				'VANESSA KIRBY “Pieces of a Woman”',
				'FRANCES MCDORMAND “Nomadland”',
				'CAREY MULLIGAN “Promising Young Woman”',
			)),
			array('title'=>'Best Supporting Actor', 'score'=>7, 'data'=>array(
				'SACHA BARON COHEN, “The Trial of the Chicago 7”',
				'DANIEL KALUUYA, “Judas and the Black Messiah”',
				'LESLIE ODOM, JR., “One Night in Miami...”',
				'PAUL RACI, “Sound of Metal”',
				'LAKEITH STANFIELD, “Judas and the Black Messiah”',
			)),
			array('title'=>'Best Supporting Actress', 'score'=>7, 'data'=>array(
				'MARIA BAKALOVA, “Borat Subsequent Moviefilm: Delivery of Prodigious Bribe to American Regime for Make Benefit Once Glorious Nation of Kazakhstan”',
				'GLENN CLOSE, “Hillbilly Elegy”',
				'OLIVIA COLMAN, “The Father”',
				'AMANDA SEYFRIED, “Mank”',
				'YUH-JUNG YOUN, “Minari”',
			)),
			array('title'=>'Best Original Screenplay', 'score'=>5, 'data'=>array(
				'“JUDAS AND THE BLACK MESSIAH,” Screenplay by Will Berson & Shaka King; Story by Will Berson & Shaka King and Kenny Lucas & Keith Lucas',
				'“MINARI” Written by Lee Isaac Chung',
				'“PROMISING YOUNG WOMAN” Written by Emerald Fennell',
				'“SOUND OF METAL” Screenplay by Darius Marder & Abraham Marder; Story by Darius Marder & Derek Cianfrance',
				'“THE TRIAL OF THE CHICAGO 7” Written by Aaron Sorkin'
			)),
			array('title'=>'Best Adapted Screenplay', 'score'=>5, 'data'=>array(
				'“BORAT SUBSEQUENT MOVIEFILM: DELIVERY OF PRODIGIOUS BRIBE TO AMERICAN REGIME FOR MAKE BENEFIT ONCE GLORIOUS NATION OF KAZAKHSTAN,” Screenplay by Sacha Baron Cohen & Anthony Hines & Dan Swimer & Peter Baynham & Erica Rivinoja & Dan Mazer & Jena Friedman & Lee Kern; Story by Sacha Baron Cohen & Anthony Hines & Dan Swimer & Nina Pedrad',
				'“THE FATHER” Screenplay by Christopher Hampton and Florian Zeller',
				'“NOMADLAND” Written for the screen by Chloé Zhao',
				'“ONE NIGHT IN MIAMI...” Written for the screen by Ramin Bahrani',
			)),
			array('title'=>'Best Foreign Language Film', 'score'=>5, 'data'=>array(
				'“ANOTHER ROUND” Denmark',
				'“BETTER DAYS” Hong Kong',
				'“COLLECTIVE” Romania',
				'“THE MAN WHO SOLD HIS SKIN” Tunisia',
				'“QUO VADIS, AIDA?” Bosnia and Herzegovina'
			)),
			array('title'=>'Best Animated Feature', 'score'=>5, 'data'=>array(
				'“ONWARD” Dan Scanlon and Kori Rae',
				'“OVER THE MOON” Glen Keane, Gennie Rim and Peilin Chou',
				'“A SHAUN THE SHEEP MOVIE: FARMAGEDDON” Richard Phelan, Will Becher and Paul Kewl',
				'“SOUL” Pete Docter and Dana Murray',
				'“WOLFWALKERS”  Tomm Moore, Ross Stewart, Paul Young and Stéphan Roelants'
			)),
			array('title'=>'Best Visual Effects', 'score'=>3, 'data'=>array(
				'“LOVE AND MONSTERS” Matt Sloan, Genevieve Camilleri, Matt Everitt and Brian Cox',
				'“THE MIDNIGHT SKY” Matthew Kasmir, Christopher Lawrence, Max Solomon and David Watkins',
				'“MULAN” Sean Faden, Anders Langlands, Seth Maury and Steve Ingram',
				'“THE ONE AND ONLY IVAN” Nick Davis, Greg Fisher, Ben Jones and Santiago Colomo Martinez',
				'“TENET” Andrew Jackson, David Lee, Andrew Lockley and Scott Fisher'
			)),
			array('title'=>'Best Film Editing', 'score'=>3, 'data'=>array(
				'“THE FATHER” Yorgos Lamprinos',
				'“NOMADLAND” Chloé Zhao',
				'“PROMISING YOUNG WOMAN” Frédéric Thoraval',
				'“SOUND OF METAL” Mikkel E. G. Nielsen',
				'“THE TRIAL OF THE CHICAGO 7” Alan Baumgarten'
			)),
			array('title'=>'Best Animated Short', 'score'=>2, 'data'=>array(
				'“BURROW” Madeline Sharafian and Michael Capbarat',
				'“GENIUS LOCI” Adrien Mérigeau and Amaury Ovise',
				'“IF ANYTHING HAPPENS I LOVE YOU” Will McCormack and Michael Govier',
				'“OPERA” Erick Oh',
				'“YES-PEOPLE” Gísli Darri Halldórsson and Arnar Gunnarsson'
			)),
			array('title'=>'Best Live Action Short', 'score'=>2, 'data'=>array(
				'“FEELING THROUGH” Doug Roland and Susan Ruzenski',
				'“THE LETTER ROOM” Elvira Lind and Sofia Sondervan',
				'“THE PRESENT” Farah Nabulsi and Ossama Bawardi',
				'“TWO DISTANT STRANGERS” Travon Free and Martin Desmond Roe',
				'“WHITE EYE” Tomer Shushan and Shira Hochman'
			)),
			array('title'=>'Best Documentary Short Subject', 'score'=>2, 'data'=>array(
				'“COLETTE” Anthony Giacchino and Alice Doyard',
				'“A CONCERTO IS A CONVERSATION” Ben Proudfoot and Kris Bowers',
				'“DO NOT SPLIT” Anders Hammer and Charlotte Cook',
				'“HUNGER WARD” Skye Fitzgerald and Michael Scheuerman',
				'“A LOVE SONG FOR LATASHA” Sophia Nahli Allison and Janice Duncan'
			)),
			array('title'=>'Best Original Score', 'score'=>3, 'data'=>array(
				'“DA 5 BLOODS” Terence Blanchard',
				'“MANK” Trent Reznor and Atticus Ross',
				'“MINARI” Emile Mosseri',
				'“NEWS OF THE WORLD” James Newton Howard',
				'“SOUL” Trent Reznor, Atticus Ross and Jon Batiste'
			)),
			array('title'=>'Best Original Song', 'score'=>3, 'data'=>array(
				'“FIGHT FOR YOU” from Judas and the Black Messiah; Music by H.E.R. and Dernst Emile II; Lyric by H.E.R. and Tiara Thomas',
				'“HEAR MY VOICE” from The Trial of the Chicago 7; Music by Daniel Pemberton; Lyric by Daniel Pemberton and Celeste Waite',
				'“HUSAVIK” from Eurovision Song Contest: The Story of Fire Saga; Music and Lyric by Savan Kotecha, Fat Max Gsus and Rickard Göransson',
				'“IO SÌ (SEEN)” from The Life Ahead (La Vita Davanti a Se); Music by Diane Warren; Lyric by Diane Warren and Laura Pausini',
				'“SPEAK NOW” from One Night in Miami...; Music and Lyric by Leslie Odom, Jr. and Sam Ashworth'
			)),
			array('title'=>'Best Production Design', 'score'=>3, 'data'=>array(
				'“THE FATHER” Production Design: Peter Francis; Set Decoration: Cathy Featherstone',
				'“MA RAINEYS BLACK BOTTOM” Production Design: Mark Ricker; Set Decoration: Karen OHara and Diana Stoughton',
				'“MANK” Production Design: Donald Graham Burt; Set Decoration: Jan Pascale',
				'“NEWS OF THE WORLD” Production Design: David Crank; Set Decoration: Elizabeth Keenan',
				'“TENET” Production Design: Nathan Crowley; Set Decoration: Kathy Lucas'
			)),
			array('title'=>'Best Cinematography', 'score'=>3, 'data'=>array(
				'“JUDAS AND THE BLACK MESSIAH” Sean Bobbitt',
				'“MANK” Erik Messerschmidt',
				'“NEWS OF THE WORLD” Dariusz Wolski',
				'“NOMADLAND” Joshua James Richards',
				'“THE TRIAL OF THE CHICAGO 7” Phedon Papamichael',
			)),
			array('title'=>'Best Costume Design', 'score'=>3, 'data'=>array(
				'”EMMA” Alexandra Byrne',
				'“MA RAINEYS BLACK BOTTOM” Ann Roth',
				'“MANK” Trish Summerville',
				'“MULAN” Bina Daigeler',
				'“PINOCCHIO” Massimo Cantini Parrini'
			)),
			array('title'=>'Best Makeup and Hairstyling', 'score'=>3, 'data'=>array(
				'“EMMA” Marese Langan, Laura Allen and Claudia Stolze',
                '“HILLBILLY ELEGY” Eryn Krueger Mekash, Matthew Mungle and Patricia Dehaney',
                '“MA RAINEYS BLACK BOTTOM” Sergio Lopez-Rivera, Mia Neal and Jamika Wilson',
                '“MANK” Gigi Williams, Kimberley Spiteri and Colleen LaBaff',
                '“PINOCCHIO” Mark Coulier, Dalia Colli and Francesco Pegoretti'
			)),
			array('title'=>'Best Documentary Feature', 'score'=>2, 'data'=>array(
				'“COLLECTIVE” Alexander Nanau and Bianca Oana',
    			'“CRIP CAMP” Nicole Newnham, Jim LeBrecht and Sara Bolder',
				'“THE MOLE AGENT” Maite Alberdi and Marcela Santibáñez',
				'“MY OCTOPUS TEACHER” Pippa Ehrlich, James Reed and Craig Foster',
				'“TIME” Garrett Bradley, Lauren Domino and Kellen Quinn'
			)),
			array('title'=>'Best Sound', 'score'=>3, 'data'=>array(
				'“GREYHOUND” Warren Shaw, Michael Minkler, Beau Borders and David Wyman',
				'“MANK” Ren Klyce, Jeremy Molod, David Parker, Nathan Nance and Drew Kunin',
				'“NEWS OF THE WORLD” Oliver Tarney, Mike Prestwood Smith, William Miller and John Pritchett',
				'“SOUL” Ren Klyce, Coya Elliott and David Parker',
				'“SOUND OF METAL” Nicolas Becker, Jaime Baksht, Michellee Couttolenc, Carlos Cortés and Phillip Bladh'
				))
	);

